### ISSUE TITLE
Magic link login throws error on setting a specific scope

### ISSUE THREAD

**Issue by InnigerM** [p2-inc/keycloak-magic-link#94]
Tried to use the magic link login via it's endpoint and a redirect to a native application. If setting the scope parameter directly via the request body following error is thrown:
```
2024-11-21T13:18:35.0537470Z 2024-11-21 14:18:35,051 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-167) Uncaught server error: java.lang.NoSuchMethodError: 'void org.keycloak.services.managers.AuthenticationManager.setClientScopesInSession(org.keycloak.sessions.AuthenticationSessionModel)'
2024-11-21T13:18:35.0537661Z 	at io.phasetwo.keycloak.magic.auth.token.MagicLinkActionTokenHandler.handleToken(MagicLinkActionTokenHandler.java:95)
2024-11-21T13:18:35.0537693Z 	at io.phasetwo.keycloak.magic.auth.token.MagicLinkActionTokenHandler.handleToken(MagicLinkActionTokenHandler.java:21)
2024-11-21T13:18:35.0537751Z 	at org.keycloak.services.resources.LoginActionsService.handleActionToken(LoginActionsService.java:691)
2024-11-21T13:18:35.0537783Z 	at org.keycloak.services.resources.LoginActionsService.executeActionToken(LoginActionsService.java:549)
2024-11-21T13:18:35.0537817Z 	at org.keycloak.services.resources.LoginActionsService$quarkusrestinvoker$executeActionToken_9df1a4d2415343036325c212be507b468d007d81.invoke(Unknown Source)
2024-11-21T13:18:35.0537846Z 	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
2024-11-21T13:18:35.0537877Z 	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
2024-11-21T13:18:35.0537907Z 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
2024-11-21T13:18:35.0537937Z 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
2024-11-21T13:18:35.0537964Z 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
2024-11-21T13:18:35.0538013Z 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
2024-11-21T13:18:35.0538042Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
2024-11-21T13:18:35.0538070Z 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
2024-11-21T13:18:35.0538098Z 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
2024-11-21T13:18:35.0538125Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2024-11-21T13:18:35.0538151Z 	at java.base/java.lang.Thread.run(Thread.java:1583)
```
## Steps to Reproduce
1. Start magic link login via `<base-url>/realms/<realm-name>/magic-link`
2. Go to link sent via payload or email
3. Receive error

Payload for magic link request:
```
{
  "email": "example@email.com",
  "client_id": "example-client",
  "redirect_uri": "native.app://auth",
  "expiration_seconds": 3600,
  "force_create": true,
  "update_profile": false,
  "update_password": false,
  "send_email": true,
  "scope": "openid profile email"
}
```

**Comment by xgp** [comment]
A NoSuchMethodError usually means your using it in an unsupported version of Keycloak. Try using the most recent jar with Keycloak 26.

**Comment by InnigerM** [comment]
Thanks, updated the jar which fixed the error.
